### ISSUE TITLE
What calib_size means?  512x512 is supported by default by engine? calib_size means the max shape?

### ISSUE THREAD

**Issue by bigmover** [NVIDIA/TensorRT-Model-Optimizer#6]
![image](https://github.com/NVIDIA/TensorRT-Model-Optimizer/assets/26063296/2662e2f4-4975-43c3-a221-17a612fd6dc6)

**Comment by jingyu-ml** [comment]
Hi @bigmover 

Since we're doing static quantization, we first need to calibrate the model. If you're unfamiliar with static quantization or quantization in general, you can consult our documentation [here](https://nvidia.github.io/TensorRT-Model-Optimizer/guides/1_quantization.html). Essentially, we perform inference to understand the input characteristics of each layer, such as their value range.

Therefore, for text-to-image tasks with Stable Diffusion, we need to input some prompts. The term 'calib-size' refers to the number of prompts we feed into the pipeline.

**Comment by jingyu-ml** [comment]
> 512x512 is supported by default by engine

Yes,

For SD 1.5, since we're using the default settings, you can modify them in our script.
